### ISSUE TITLE
Get an account login error after about 30 minutes 

### ISSUE THREAD

**Issue by andrewcliffoutlook** [pnbruckner/ha-life360#25] opened 2024-06-05 21:33 UTC
I am able to add the integration and login using email address and password and have also successfully used the token method and the integration successfully retrieves my circle but after about 30 minutes I get a 403 error on the members in my circle and it all stops working and I get a account repair message in Homeassistant and the Life360 online entity goes into a disconnected state

**Comment by pnbruckner** [comment] 2024-06-05 23:26
Hmm, they may have changed things again!

**Comment by andrewcliffoutlook** [comment] 2024-06-06 10:21
I can share debug logs with you if that helps

**Comment by andrewcliffoutlook** [comment] 2024-06-06 10:32
Looking at your code for life360 the issue is being caused by the following code:

case HTTP_Error.FORBIDDEN:
                        raise LoginError(err_msg) from exc

I think in reality when the life360 api gives this response it is not a terminal error and is much like the too many requests error.  If you wait and try again then this error won't occur again. 

I am basing this on the fact that if enable the account again it all works again for a while and then later fails again with this error.

**Comment by pnbruckner** [comment] 2024-06-06 13:23
Yeah, that might be the case. I had considered always retrying 403, but never saw it for anything other than the query for Circles.

I think I'll go ahead and always retry 403 & 429, for all messages. But since the Member query happens every 5 seconds, I'll have to give some thought on the best way to handle these errors for that query.

**Comment by pnbruckner** [comment] 2024-06-06 15:04
Actually, I did add some retrying of error 403 for all queries (except for Circles, which is handled differently.)

It will retry after an error 403 up to two times for each query, but it does so immediately. You can see this in the log (if you have debug enabled.) There should be a DEBUG message from `[life360.api]` that contains "`Request error:`", followed by a DEBUG message from `[custom_components.life360.coordinator]` that contains "`will retry`".

Do you see those in your log? Do you ever see where this is "successful" (i.e., it retries and the query works, so it doesn't result in the account being disabled)? Or do you only see where it retries but is unsuccessful, resulting in the account getting disabled?

How to handle this really depends on the behavior of the server, which is pretty unpredictable. A simple thing to try would be to add some small amount of delay, like say, 5 seconds, after the error (instead of zero, which is what it uses now.) That would work if it was just a "glitch", and the server would process the query normally very quickly. Or, I suppose, it could be bumped up to 30 seconds, a minute, whatever. And possibly the retry count limit could be bumped up from 2 as well. I'm pretty sure it would just cause the current entity update to take longer, and assuming it does eventually work, it would just go back to updating every 5 seconds. Or really, 5 seconds between update attempts, where each attempt would take as long as necessary, up to the limit of retrying. I think there has to be some cutoff, otherwise it could just never update or error out.

Anyway, if you have the ability to modify the code, and are willing to try some experiments, I could suggest what to try.

**Comment by andrewcliffoutlook** [comment] 2024-06-06 17:07
Hi Phil

I do have the ability to make code changes and would be happy to experiment.

Kind regards

Andrew Cliff

Sent from my phone

On 6 Jun 2024, at 16:04, Phil Bruckner ***@***.***> wrote:

﻿

Actually, I did add some retrying of error 403 for all queries (except for Circles, which is handled differently.)

It will retry after an error 403 up to two times for each query, but it does so immediately. You can see this in the log (if you have debug enabled.) There should be a DEBUG message from [life360.api] that contains "Request error:", followed by a DEBUG message from [custom_components.life360.coordinator] that contains "will retry".

Do you see those in your log? Do you ever see where this is "successful" (i.e., it retries and the query works, so it doesn't result in the account being disabled)? Or do you only see where it retries but is unsuccessful, resulting in the account getting disabled?

How to handle this really depends on the behavior of the server, which is pretty unpredictable. A simple thing to try would be to add some small amount of delay, like say, 5 seconds, after the error (instead of zero, which is what it uses now.) That would work if it was just a "glitch", and the server would process the query normally very quickly. Or, I suppose, it could be bumped up to 30 seconds, a minute, whatever. And possibly the retry count limit could be bumped up from 2 as well. I'm pretty sure it would just cause the current entity update to take longer, and assuming it does eventually work, it would just go back to updating every 5 seconds. Or really, 5 seconds between update attempts, where each attempt would take as long as necessary, up to the limit of retrying. I think there has to be some cutoff, otherwise it could just never update or error out.

Anyway, if you have the ability to modify the code, and are willing to try some experiments, I could suggest what to try.

**Comment by pnbruckner** [comment] 2024-06-06 17:16
Great! In `custom_components/life360/coordinatory.py`, on line 491, which should look like this:
```python
delay = 0
```
change the zero to some number of seconds. That will cause it to wait after an error 403 before trying again.

If you want to increase the max number of retries, then in the same file, just above on line 485, which should look like this:
```python
and login_error_retries < MAX_LOGIN_ERROR_RETRIES
```
change `MAX_LOGIN_ERROR_RETRIES` to a number larger than 2 (which is its current value.)

**Comment by James62370** [comment] 2024-06-07 02:09
I'm not sure if this is related, but I started getting a similar error, when I logged out of the life360 website.  I got a new token and didn't log out this time, and the add-on has stayed connected for a few days now.

**Comment by andrewcliffoutlook** [comment] 2024-06-07 14:05
I have applied the changes you recommended setting a 30 second retry when it gets a login error, increasing the max login error retries to 10 and I also changed the update delta to 10 seconds.

With these changes it seems to be stable and it has been running for 3 hours without disconnecting and disabling the account.

Kind regards

Andrew Cliff

Sent from my phone

On 6 Jun 2024, at 18:17, Phil Bruckner ***@***.***> wrote:

﻿

Great! In custom_components/life360/coordinatory.py, on line 491, which should look like this:

delay = 0

change the zero to some number of seconds. That will cause it to wait after an error 403 before trying again.

If you want to increase the max number of retries, then in the same file, just above on line 485, which should look like this:

and login_error_retries < MAX_LOGIN_ERROR_RETRIES

change MAX_LOGIN_ERROR_RETRIES to a number larger than 2 (which is its current value.)

**Comment by pnbruckner** [comment] 2024-06-07 15:07
Good to hear!

But the server often changes its behavior now and then. There have been times I've seen more errors than at other times.

Could you check your log to see if you're getting any 403 (or 429) errors? From above:

> It will retry after an error 403 up to two times for each query, but it does so immediately. You can see this in the log (if you have debug enabled.) There should be a DEBUG message from [life360.api] that contains "Request error:", followed by a DEBUG message from [custom_components.life360.coordinator] that contains "will retry".

I'd really like some details on how often the errors happen, how many retries are needed, etc.

**Comment by James62370** [comment] 2024-06-07 15:12
Curious, is it a requirement to stay logged on with the life360  website, or does that invalidate the token upon logging out?

**Comment by pnbruckner** [comment] 2024-06-07 15:17
> Curious, is it a requirement to stay logged on with the life360 website, or does that invalidate the token upon logging out?

Your guess is as good as mine. But, FWIW, whenever I've used/tested this method, I've never logged out of the website. I simply closed the browser.

**Comment by andrewcliffoutlook** [comment] 2024-06-07 15:34
I am getting those but with the 30 second retry it doesn't fail on the retry.

Kind regards

Andrew Cliff

Sent from my phone

On 7 Jun 2024, at 16:07, Phil Bruckner ***@***.***> wrote:

﻿

Good to hear!

But the server often changes its behavior now and then. There have been times I've seen more errors than at other times.

Could you check your log to see if you're getting any 403 (or 429) errors? From above:

It will retry after an error 403 up to two times for each query, but it does so immediately. You can see this in the log (if you have debug enabled.) There should be a DEBUG message from [life360.api] that contains "Request error:", followed by a DEBUG message from [custom_components.life360.coordinator] that contains "will retry".

I'd really like some details on how often the errors happen, how many retries are needed, etc.

**Comment by Menz01** [comment] 2024-06-20 18:31
i am getting the account logon errors and as soon as it's "repaired" it shows as broken again. it still seems to be working however as the map shows where my family is. not sure why the error won't go away

**Comment by Menz01** [comment] 2024-06-20 23:41
@pnbruckner actually, i was wrong... life360 is not working. i have other things i use for tracking which is why my family is on the map. so is life360 broken again?

**Comment by pnbruckner** [comment] 2024-06-21 12:59
> so is life360 broken again?

It's working for many people, including myself. I've only heard minimal reports about this scenario, and since I can't reproduce the problem myself, I need more input than I have so far to decide what to do.

Is there any way you can try the changes described above yourself and let me know the minimum values that make it work for you, assuming it does?

Also, @andrewcliffoutlook , same question to you?

I'd like to release a change with more retrying of this error, but since I can't reproduce the problem, I need your input. I don't just want to use large values, or retry forever.

**Comment by Menz01** [comment] 2024-06-21 14:02
@pnbruckner i am really bad at making coding changes and will probably mess it up even more. so i wanted to perhaps "show" you what i am "seeing"

here is the error i see in settings screen
![accont error](https://github.com/pnbruckner/ha-life360/assets/31291495/08d8ee75-7510-4b09-b5ba-93fc04faad26)

but if i go to the integrations screen it does not look like its broken (i have other integrations that have red boxes around them showing something is wrong)
![not showing as broken](https://github.com/pnbruckner/ha-life360/assets/31291495/2e06d3ac-fbed-458d-a354-6bb437cba264)

and if i go to the service itself i see this
![open integration](https://github.com/pnbruckner/ha-life360/assets/31291495/6564e653-6813-4296-bf0e-91b47fc896e8)

and here is the most odd part.... if i enable debugging and then disable it and download the log there are no errors for life360 in the log at all

**Comment by pnbruckner** [comment] 2024-06-21 14:24
This is all expected. When the error occurs enough, the repair issue is created, and the account is disabled. If you click on the repair issue, it should tell you to go to the Life360 integration entry page and "then click CONFIGURE and modify account". When you do, you should see it is disabled.

Since the account is disabled, the entities will not update. In fact, what you're seeing when you look at the integration entities is that they are all "not provided". If you look at the state of those entities, they will all be unavailable and with a "restored: true" attribute.

When you re-enable the account, after it is able to retrieve the list of Circles & Members, the entities should be fully created again. But if it runs into the same problem (too many error 403), it will just disable the account and and recreate the repair issue.

Do you have the ability to edit files in config/custom_components? If so, it should be very easy to change it, so it delays between retries and retries more often before giving up. I would really appreciate if you could give it a try. It's not working for you as it is, so what do you have to lose?

**Comment by Menz01** [comment] 2024-06-21 18:50
so i re-enabled the account (missed that, thank you) and i have restarted i even waited a few hours and went driving around, but all my entities still shows as disabled and i can't re-enable them

**Comment by pnbruckner** [comment] 2024-06-21 18:52
What errors or warnings do you see in the system log? It should at least say something about retrieving Circles & Members.

**Comment by petebanham** [comment] 2024-06-22 14:53
Mine seems to have broken over night as well.  I have a repair issue showing and the account is disabled. If I enable it, it just disables again straight away and there is nothing  in the system log from Life 360

**Comment by rleongcs** [comment] 2024-06-22 16:02
Mine was also broken and I have to remove the disabled account and re-add the account for it to work again. Not sure if it will be disabled again or not. I am using username and password rather than token.

**Comment by Menz01** [comment] 2024-06-22 16:16
> What errors or warnings do you see in the system log? It should at least say something about retrieving Circles & Members.

i looked in the logs and its telling me with a warning that it has retrieved all circles and members but still all my members are missing
![image](https://github.com/pnbruckner/ha-life360/assets/31291495/e20e0dec-2aca-4318-bd14-b87b16b1701a)
![image](https://github.com/pnbruckner/ha-life360/assets/31291495/4602f5af-d2ad-481e-b207-f3004f9685ba)


i deleted my member entities thinking they needed to be deleted since they were all disabled and none have returned. i even deleted the integration and re-added it back and they are still missing

**Comment by andrewcliffoutlook** [comment] 2024-06-22 19:43
Hi Phil

I have just upgraded to HA 2024.6.4 and Life360 won't initialise.  It could well be that a change made with this version is incompatible with your implementation.

Kind regards

Andrew Cliff

Sent from my phone

On 21 Jun 2024, at 19:53, Phil Bruckner ***@***.***> wrote:

﻿

What errors or warnings do you see in the system log? It should at least say something about retrieving Circles & Members.

**Comment by andrewcliffoutlook** [comment] 2024-06-22 19:45
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 20:42:16 (1 occurrences)
Last logged: 20:42:16

Error setting up entry Life360 for life360
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/life360/__init__.py", line 123, in async_setup_entry
    await async_process_data()
  File "/config/custom_components/life360/__init__.py", line 104, in async_process_data
    await asyncio.gather(*coros)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/life360/coordinator.py", line 707, in _async_update_data
    raw_member_data = await self._coordinator.get_raw_member_data(self._mid)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/life360/coordinator.py", line 170, in get_raw_member_data
    raw_member_list = await asyncio.gather(
                      ^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

Logs for initialisation error.

Kind regards

Andrew Cliff

Sent from my phone

On 22 Jun 2024, at 20:43, Andrew Cliff ***@***.***> wrote:

﻿ Hi Phil

I have just upgraded to HA 2024.6.4 and Life360 won't initialise.  It could well be that a change made with this version is incompatible with your implementation.

Kind regards

Andrew Cliff

Sent from my phone

On 21 Jun 2024, at 19:53, Phil Bruckner ***@***.***> wrote:

﻿

What errors or warnings do you see in the system log? It should at least say something about retrieving Circles & Members.

**Comment by NateRobinsonS** [comment] 2024-06-23 13:19
I can confirm that `delay = 30` seems to work for me. I didn't need to change anything else.

**Comment by pnbruckner** [comment] 2024-06-24 15:40
> I have just upgraded to HA 2024.6.4 and Life360 won't initialise. It could well be that a change made with this version is incompatible with your implementation.

I tested with that version and it's not a problem for me. I think the exception you're seeing (thanks for posting from the log!) is an indirect result of the basic problem of some people seeing error 403 while fetching Member data (while most don't.)

I'll be posting a beta soon that increases the delay (in this scenario) from zero to ten seconds, and bumps the maximum retry count from 2 to 30, which should allow the integration to handle these error 403's, assuming the server responds with data instead of the error within 5 minutes. It also tries to fix the improperly handled exception (although it's hard for me to verify these fixes since I don't see these errors.)

**Comment by pnbruckner** [comment] 2024-06-24 15:48
Everyone who has experienced this problem, please try the 0.5.3b0 beta release and let me know if it helps.

**Comment by Menz01** [comment] 2024-06-24 16:05
> Everyone who has experienced this problem, please try the 0.5.3b0 beta release and let me know if it helps.

just tried it as well. entities still not updating. i did take a screenshot of the log book

![image](https://github.com/pnbruckner/ha-life360/assets/31291495/dcb78ade-49df-4a37-8d88-0ec41a1733ed)

**Comment by pnbruckner** [comment] 2024-06-24 16:35
@Menz01 I see you are getting error 401, not 403. So far, everyone has said (or implied) the problem is error 403, although when I ask for these details, unfortunately, people don't always provide them, which makes it difficult to get to the root of the problem.

The changes in 0.5.3b0 only attempt to handle error 403 better, not error 401.

Error 401 is "unauthorized", which is another type of "login" error. I don't think retrying will solve error 401. The only thing I can suggest is to update the account credentials. Are you using username & password? Or are you using a browser to capture the access token?

**Comment by Menz01** [comment] 2024-06-24 16:36
i am using the token and it accepts the token without error

**Comment by petebanham** [comment] 2024-06-24 16:47
> Unfortunately still the same for me, the account shows as disabled. Let's me toggle it to enabled but doesn't stay enabled. I haven't removed and readded the integration or account if either of those are needed ?

So I just tried removing the account and immediately re adding it and after an initial failed to retrieve circle.... error in the logs, the entries are all back. Thanks for your on going work with this

**Comment by pnbruckner** [comment] 2024-06-24 17:10
@Menz01 it accepts the token without trying to test if it works. I did have some code in before that tried to test the token at that point, but it didn't really work very well (mainly, I think, due to the error 403 issue), so I removed it. So, being able to enter the token does not mean it will actually work.

There was a [report above](https://github.com/pnbruckner/ha-life360/issues/25#issuecomment-2153725698) that logging out in the web browser used to obtain the token can lead to problems. Try grabbing a new access token, but after getting the token (and copying it into HA), do NOT log out in the browser you used to get the token. Just close that browser.

**Comment by pnbruckner** [comment] 2024-06-24 17:14
> So I just tried removing the account and immediately re adding it and after an initial failed to retrieve circle.... error in the logs, the entries are all back. Thanks for your on going work with this

I'm glad it's working again for you, but honestly, this doesn't make sense. You shouldn't have to remove the account from the integration and add it back in. Just enabling it should work. And please remember, the message in the log about not being able to retrieve the Circles & Members fully is a warning, not an error. It retries in the "background" until it's successful, at which time the entities should come fully back, too. Unless, of course, there are other actual errors that prevent it that from happening.

**Comment by Menz01** [comment] 2024-06-24 17:23
> @Menz01 it accepts the token without trying to test if it works. I did have some code in before that tried to test the token at that point, but it didn't really work very well (mainly, I think, due to the error 403 issue), so I removed it. So, being able to enter the token does not mean it will actually work.
> 
> There was a [report above](https://github.com/pnbruckner/ha-life360/issues/25#issuecomment-2153725698) that logging out in the web browser used to obtain the token can lead to problems. Try grabbing a new access token, but after getting the token (and copying it into HA), do NOT log out in the browser you used to get the token. Just close that browser.

so i got a new token and its working again. however, maybe its just me but that token is very hard to find and it took me 3 browsers to find it. following the guides i could not find any "token" entries when i used firefox and chrome. however when i followed the same procedures in edge, i found two token entries and one had the token and it was different from the one i previously had. not sure why i could not find them in chrome when edge and chrome are almost the same.

**Comment by pnbruckner** [comment] 2024-06-25 19:46
@andrewcliffoutlook @rleongcs @NateRobinsonS @petebanham, have any of you tried 0.5.3b0, and if so, any better?

**Comment by pnbruckner** [comment] 2024-06-25 19:47
> I'm not sure if this is related, but I started getting a similar error, when I logged out of the life360 website. I got a new token and didn't log out this time, and the add-on has stayed connected for a few days now.

@James62370, just curious, when you said, "getting a similar error", did you mean error 401?

**Comment by petebanham** [comment] 2024-06-25 20:13
Phil, it worked for me but only after I removed and readded my account.

**Comment by andrewcliffoutlook** [comment] 2024-06-25 20:29
Hi Phil

I had previously made similar parameter changes to the code so it provides a similar level of stability.  It generally stays active for between 18 and 24 hours and then I need to repair and enable.

[image0.png]
Kind regards

Andrew Cliff

Sent from my phone

On 25 Jun 2024, at 20:47, Phil Bruckner ***@***.***> wrote:

﻿

@andrewcliffoutlook<https://github.com/andrewcliffoutlook> @rleongcs<https://github.com/rleongcs> @NateRobinsonS<https://github.com/NateRobinsonS> @petebanham<https://github.com/petebanham>, have any of you tried 0.5.3b0, and if so, any better?

**Comment by pnbruckner** [comment] 2024-06-25 20:37
@petebanham @andrewcliffoutlook et al, it's really important to let me know which error causes the account to get disabled (and a repair issue to be created.) Errors 401 & 403 are handled differently. It seems error 403 can be recovered from by retrying, whereas, as far as I know, error 401 cannot be.

To my knowledge, error 401 can only be resolved by getting a new access token. If you're using username & password, you should not have to delete & re-add the account. Just (re)enabling it will cause a new access token to be automatically fetched. Of course, if you're using the access token type of account, then you have to "manually" get a new access token using Life360's website and the browser's dev tools.

So, I'd really like to know, if/when anyone has problems that don't resolve themselves:

1) Exactly what error did you get (e.g., 401 or 403)?
2) Did you have to get a new access token (either manually, or via disabling/re-enabling the account) to get it working again?

**Comment by andrewcliffoutlook** [comment] 2024-06-25 21:00
This error originated from a custom integration.

Logger: custom_components.life360.coordinator
Source: custom_components/life360/coordinator.py:546
integration: Life360 (documentation, issues)
First occurred: 24 June 2024 at 20:51:19 (3 occurrences)
Last logged: 19:21:28
***@***.***: while getting data for Andrew Cliff from Cliff family Circle: aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api-cloudfront.life360.com/v3/circles/c6ab40ce-7464-4417-9b70-0c4d95fb052a/members/7bbb0adf-ce85-4750-8f30-6efe03294894'); status: 403



Kind regards

Andrew Cliff

Sent from my phone

On 25 Jun 2024, at 21:37, Phil Bruckner ***@***.***> wrote:

﻿

@petebanham<https://github.com/petebanham> @andrewcliffoutlook<https://github.com/andrewcliffoutlook> et al, it's really important to let me know which error causes the account to get disabled (and a repair issue to be created.) Errors 401 & 403 are handled differently. It seems error 403 can be recovered from by retrying, whereas, as far as I know, error 401 cannot be.

To my knowledge, error 401 can only be resolved by getting a new access token. If you're using username & password, you should not have to delete & re-add the account. Just (re)enabling it will cause a new access token to be automatically fetched. Of course, if you're using the access token type of account, then you have to "manually" get a new access token using Life360's website and the browser's dev tools.

So, I'd really like to know, if/when anyone has problems that don't resolve themselves:

  1.  Exactly what error did you get (e.g., 401 or 403)?
  2.  Did you have to get a new access token (either manually, or via disabling/re-enabling the account) to get it working again?

**Comment by SkoobyDu** [comment] 2024-06-25 21:55
Hi,

Thank for your world in this, I'm getting error 403 as others.

I'm using the username and password option. 

This error originated from a custom integration.

Logger: custom_components.life360.coordinator
Source: custom_components/life360/coordinator.py:542
integration: Life360 (documentation, issues)
First occurred: 22:09:32 (2 occurrences)
Last logged: 22:47:25

steve.irving@outlook.com: while getting data for Eve Irving from eve Circle: aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api-cloudfront.life360.com/v3/circles/REDACTED/members/REDACTED'); status: 403

**Comment by SkoobyDu** [comment] 2024-06-25 21:57
Hi,

Thank for your world in this, I'm getting error 403 as others.

I'm using the username and password option. 

This error originated from a custom integration.

Logger: custom_components.life360.coordinator
Source: custom_components/life360/coordinator.py:542
integration: Life360 (documentation, issues)
First occurred: 22:09:32 (2 occurrences)
Last logged: 22:47:25

xxxxx.xxxxxx@xxxxxx.xxx: while getting data for xxx xxxxx, from xxx Circle: aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api-cloudfront.life360.com/v3/circles/REDACTED/members/REDACTED'); status: 403

**Comment by pnbruckner** [comment] 2024-06-25 22:40
@SkoobyDu have you tried 0.5.3b0 yet?

**Comment by petebanham** [comment] 2024-06-26 06:05
> @petebanham @andrewcliffoutlook et al, it's really important to let me know which error causes the account to get disabled (and a repair issue to be created.) Errors 401 & 403 are handled differently. It seems error 403 can be recovered from by retrying, whereas, as far as I know, error 401 cannot be.
> 
> To my knowledge, error 401 can only be resolved by getting a new access token. If you're using username & password, you should not have to delete & re-add the account. Just (re)enabling it will cause a new access token to be automatically fetched. Of course, if you're using the access token type of account, then you have to "manually" get a new access token using Life360's website and the browser's dev tools.
> 
> So, I'd really like to know, if/when anyone has problems that don't resolve themselves:
> 
> 1. Exactly what error did you get (e.g., 401 or 403)?
> 2. Did you have to get a new access token (either manually, or via disabling/re-enabling the account) to get it working again?

@pnbruckner  mine has been stable since the upgrade and remove/readd of account but if it happens again I will look for the error.  Should I be looking anywhere other than the normal  system log please as last time I dont think there was anything in there?

**Comment by SkoobyDu** [comment] 2024-06-26 06:37
> @SkoobyDu have you tried 0.5.3b0 yet?

Hi, I've installed the beta after finding this thread and posting my post above, I'll let you know if it happens again.

**Comment by pnbruckner** [comment] 2024-06-26 13:24
> Should I be looking anywhere other than the normal system log please as last time I dont think there was anything in there?

@petebanham, just the normal system log. Unless I've totally screwed up somewhere, the account won't get disabled (and a repair issue created) without an error showing up in the system log.

If you wouldn't mind, you could also enable debug for the integration. If you have any problems again, DEBUG messages might help explain exactly what's going on.

**Comment by petebanham** [comment] 2024-06-26 14:17
@pnbruckner I have turned dedug on for the integration on in case it happens again.  Re the main log, it may be that i restarted HA before checking it, I cant remember, but the UI only then shows stuff since the restart,  next time will def check 1st!

**Comment by pnbruckner** [comment] 2024-06-26 14:27
> Re the main log, it may be that i restarted HA before checking it, I cant remember, but the UI only then shows stuff since the restart, next time will def check 1st!

Yep, that's true. But, if you have direct access to files in the config directory, there should be a file named home-assistant.log.1, which is the entire log from the previous run (i.e., before restarting.)

**Comment by SkoobyDu** [comment] 2024-06-26 19:19
> > @SkoobyDu have you tried 0.5.3b0 yet?
> 
> Hi, I've installed the beta after finding this thread and posting my post above, I'll let you know if it happens again.

Hi, I can confirm I've had no errors or warning messages in settings for 24hrs running your beta.

Thank you

**Comment by SkoobyDu** [comment] 2024-07-01 09:17
> 403

Hi, 
Sorry to report, but the 403 error has returned over the weekend.

**Comment by pnbruckner** [comment] 2024-07-01 13:53
@SkoobyDu you can try editing `custom_components/life360/const.py`. The values you should increase are:
```python
LTD_LOGIN_ERROR_RETRY_DELAY = 10
MAX_LTD_LOGIN_ERROR_RETRIES = (60 // LTD_LOGIN_ERROR_RETRY_DELAY) * 5
```
The first is the amount of delay (in seconds) between retries, and the second is how long it will retry (in seconds) before it gives up and logs the error, disables the account, etc.

If you find a set of values that work well for you, let me know. This is all just guessing on my part because I don't see these errors.

**Comment by SkoobyDu** [comment] 2024-07-01 14:25
> @SkoobyDu you can try editing `custom_components/life360/const.py`. The values you should increase are:
> 
> ```python
> LTD_LOGIN_ERROR_RETRY_DELAY = 10
> MAX_LTD_LOGIN_ERROR_RETRIES = (60 // LTD_LOGIN_ERROR_RETRY_DELAY) * 5
> ```
> 
> The first is the amount of delay (in seconds) between retries, and the second is how long it will retry (in seconds) before it gives up and logs the error, disables the account, etc.
> 
> If you find a set of values that work well for you, let me know. This is all just guessing on my part because I don't see these errors.

Thank you, I've doubled both values initially, I'll let you know how I get on.

**Comment by pnbruckner** [comment] 2024-07-05 14:24
Anyone still having problems, please try 0.5.3b1 and let me know how it goes.

**Comment by andrewcliffoutlook** [comment] 2024-07-05 16:35
What changes have you made?

Kind regards

Andrew Cliff

Sent from my phone

On 5 Jul 2024, at 15:24, Phil Bruckner ***@***.***> wrote:

﻿

Anyone still having problems, please try 0.5.3b1 and let me know how it goes.

**Comment by pnbruckner** [comment] 2024-07-05 16:52
https://github.com/pnbruckner/ha-life360/compare/master...0.5.3b2

Also, see https://github.com/pnbruckner/ha-life360/releases.

**Comment by petebanham** [comment] 2024-07-06 07:06
Mine did it again the night before last but upgrading to this version
yesterday seems to have sorted it.  I am away at the moment so can't access
backend logs etc to see what my error was sorry.

**Comment by woodmj74** [comment] 2024-07-06 12:07
https://github.com/pnbruckner/ha-life360/compare/master...0.5.3b2 working for a UK user.

@pnbruckner thank you as always for your on going commitment to this

**Comment by SkoobyDu** [comment] 2024-07-08 09:43
> [master...0.5.3b2](https://github.com/pnbruckner/ha-life360/compare/master...0.5.3b2)
> 
> Also, see https://github.com/pnbruckner/ha-life360/releases.

Hi 0.5.3b2 hasn't created any errors from me in the few days its been running :)

**Comment by Menz01** [comment] 2024-07-08 11:06
It hasn't created any errors per se, but it also has not populated my
members in my circle so I do not have any entities either. So it's not
working for me

**Comment by pnbruckner** [comment] 2024-07-08 13:25
Even when one of the new beta versions "works", I'm pretty sure it's not working very well. I.e., it's very possible it's having to retry error 403 very often, meaning that updates are coming very slowly (minutes apart instead of seconds apart.) I'm not sure I would consider that "working." In fact, I've just about given up on this and have stopped using the integration myself.

It was one thing when requesting the list of Circles often resulted in error 403 or 429. That information doesn't change often, and once obtained, really doesn't need to be obtained again, so retrying for a long time was ok. But now that the server is responding with error 403 while requesting member location data, that really "throws a wrench in." I currently have no idea how to avoid these errors, and that may be by design. I'm not sure there is a "fix" for this.

**Comment by smarthomefamilyverrips** [comment] 2024-07-09 15:03
> Even when one of the new beta versions "works", I'm pretty sure it's not working very well. I.e., it's very possible it's having to retry error 403 very often, meaning that updates are coming very slowly (minutes apart instead of seconds apart.) I'm not sure I would consider that "working." In fact, I've just about given up on this and have stopped using the integration myself.
> 
> It was one thing when requesting the list of Circles often resulted in error 403 or 429. That information doesn't change often, and once obtained, really doesn't need to be obtained again, so retrying for a long time was ok. But now that the server is responding with error 403 while requesting member location data, that really "throws a wrench in." I currently have no idea how to avoid these errors, and that may be by design. I'm not sure there is a "fix" for this.

@pnbruckner I am afraid I have to join your conclusion and admit that most likely the integration is dead (again) unfortunatly. I tryed several things but while others still seem to have some form of succes myself I only can get the integration authenticated when using acces token while before I always used email/password and even then it never is retrieving the members in my circle as tracker entities.... I think I will join you and just go on and delete all integration how sad it may be.

Anyway I wanna thank you for all the time and energy you did put in this over the years!! 💯

**Comment by andrewcliffoutlook** [comment] 2024-07-09 15:42
Hi Phil

Since your last update the integration has been stable for me and is now usable for my use case which I use to arm and disarm and alarm, heating and external cameras when everyone in my circle has left or on the arrival of the first person.


Kind regards

Andrew Cliff

Sent from my phone

On 8 Jul 2024, at 14:25, Phil Bruckner ***@***.***> wrote:

﻿

Even when one of the new beta versions "works", I'm pretty sure it's not working very well. I.e., it's very possible it's having to retry error 403 very often, meaning that updates are coming very slowly (minutes apart instead of seconds apart.) I'm not sure I would consider that "working." In fact, I've just about given up on this and have stopped using the integration myself.

It was one thing when requesting the list of Circles often resulted in error 403 or 429. That information doesn't change often, and once obtained, really doesn't need to be obtained again, so retrying for a long time was ok. But now that the server is responding with error 403 while requesting member location data, that really "throws a wrench in." I currently have no idea how to avoid these errors, and that may be by design. I'm not sure there is a "fix" for this.

**Comment by pnbruckner** [comment] 2024-07-09 16:00
@andrewcliffoutlook, et al, please see: https://github.com/pnbruckner/ha-life360/issues/30#issuecomment-2217832972

I would be interested to see how long (i.e., how many retries) it takes to actually get a member location update from the server. Just because it's not disabling the account does not mean it's actually getting timely updates from the server.

**Comment by andrewcliffoutlook** [comment] 2024-07-09 17:38
How do I determine that?  At present I am not seeing a noticeable delay as my location based automations are working as expected i.e. the house alarm is disabled by the time we get out the car and get to the front door.


Kind regards

Andrew Cliff

Sent from my phone

On 9 Jul 2024, at 17:01, Phil Bruckner ***@***.***> wrote:

﻿

@andrewcliffoutlook<https://github.com/andrewcliffoutlook>, et al, please see: #30 (comment)<https://github.com/pnbruckner/ha-life360/issues/30#issuecomment-2217832972>

I would be interested to see how long (i.e., how many retries) it takes to actually get a member location update from the server. Just because it's not disabling the account does not mean it's actually getting timely updates from the server.

**Closed** 2024-08-09 15:20 UTC
