### ISSUE TITLE
custom_components/life360 fix stopped working

### ISSUE THREAD

**Issue by fenen001** [pnbruckner/ha-life360#9] opened 2024-01-04 07:18 UTC
One week ago I added the latest fix for Life360 (custom_components/life360) and that worked but since yesterday the connection stopped and now again the same issues with authentication. Any idea what happened? Did Life360 changed something again....?

Thanks for your help!

**Comment by ikarus-71** [comment] 2024-01-04 08:10
Same here, I am getting "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" error in the integration.
Thanks

**Comment by fenen001** [comment] 2024-01-04 08:43
I have exactly the same error: "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

**Comment by pnbruckner** [comment] 2024-01-04 14:18
Duplicate of #8

**Closed** 2024-01-04 14:18 UTC

**Comment by pnbruckner** [comment] 2024-01-04 14:20
I should add, this is a new error, but the bottom line is, Life360 seems to have actively started to shut out non-supported uses of their API. Unless something significant changes to open up their API again, I'm not planning on trying to play catchup.

**Comment by ikarus-71** [comment] 2024-01-04 14:23
Thanks Phil, I think you had done more than enough upto now. It is time to move on for us from life 360

**Comment by fenen001** [comment] 2024-01-05 07:14
Thanks, what would be a good replacement for Life360 in Home Assistant?

**Comment by pnbruckner** [comment] 2024-01-05 14:26
I've been suggesting checking these community forum topics:

[Looking for Life360 alternative for presence detection for home alarm - Configuration - Home Assistant Community (home-assistant.io)](https://community.home-assistant.io/t/looking-for-life360-alternative-for-presence-detection-for-home-alarm/664108)

[Device Tracker, Best echange for Life360 - Configuration - Home Assistant Community (home-assistant.io)](https://community.home-assistant.io/t/device-tracker-best-echange-for-life360/665944)

My personal preference is https://www.home-assistant.io/integrations/google_maps/. Old and a bit tricky to set up, but I've been using it for a long time (combined, in some cases, with Life360 via my composite integration), and it's pretty much "just worked".

**Comment by fenen001** [comment] 2024-01-05 14:45
Thank you for the information, I will have a look.
