### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by piro73** [pnbruckner/ha-life360#11] opened 2024-01-08 17:20 UTC
Hi,
during configuration I receive an "Invalid authentication" error in the log I see this error.

2024-01-08 18:11:31.144 DEBUG (MainThread) [life360.api] Error while getting authorization token, attempt 1: ClientResponseError(RequestInfo(url=URL('https://api-cloudfront.life360.com/v3/oauth2/token'), method='POST', headers=<CIMultiDictProxy('Host': 'api-cloudfront.life360.com', 'user-agent': 'com.life360.android.safetymapd/KOKO/23.49.0 android/13', 'Accept': 'application/json', 'cache-control': 'no-cache', 'Authorization': 'Basic Y2F0aGFwYWNyQVBoZUtVc3RlOGV2ZXZldnVjSGFmZVRydVl1ZnJhYzpkOEM5ZVlVdkE2dUZ1YnJ1SmVnZXRyZVZ1dFJlQ1JVWQ==', 'Accept-Encoding': 'gzip, deflate, br', 'Content-Length': '71', 'Content-Type': 'application/x-www-form-urlencoded')>, real_url=URL('https://api-cloudfront.life360.com/v3/oauth2/token')), (), status=403, message='Forbidden', headers=<CIMultiDictProxy('Date': 'Mon, 08 Jan 2024 17:11:31 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'max-age=15', 'Expires': 'Mon, 08 Jan 2024 17:11:46 GMT', 'Set-Cookie': '__cf_bm=UQ2wed2zZ4kk08G0z08hgD894F8h9mw9PO4tl.Oei6I-1704733891-1-AaIsuW1OGKJ6H3cfPe7eUyTqh6MUPGTuW6sIp226FItBBoZYji++s0o2SbFuaFOjXMyc2IJMD40rxGoomFQfgwY=; path=/; expires=Mon, 08-Jan-24 17:41:31 GMT; domain=.life360.com; HttpOnly; Secure; SameSite=None', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '84260f637ee1bb23-MXP', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400')>)
2024-01-08 18:11:31.144 DEBUG (MainThread) [custom_components.life360] Login error: ClientResponseError: 403, message='Forbidden', url=URL('https://api-cloudfront.life360.com/v3/oauth2/token')

The integration worked until last week and then nothing. I removed and reinstalled the integration but now I keep getting the same error.

can you suggest me something to test?

Mirko

**Comment by pnbruckner** [comment] 2024-01-08 17:36
Duplicate of #8, #9 & #10

**Closed by pnbruckner** 2024-01-08 17:36 UTC
